config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  resources :adventures, only: [:index, :new, :create, :show, :edit, :update, :destroy ] do
    resources :messages, only: [:create]
    member do
      post 'attend'
    end
  end
  get 'adventures/intro', to: 'adventures#intro'
  
  resources :users, only: [:show, :update]

  resources :characters, only: [:show, :new, :create, :edit, :update, :destroy] do
    member do
      patch 'set_active'
    end
  end

  # Defines the root path route ("/")
  root "adventures#intro"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :adventures, foreign_key: :creator_id, dependent: :destroy
  has_many :characters, dependent: :destroy
  has_one :active_character, class_name: 'Character', foreign_key: :active_user_id
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user! 

  def show
    @user = User.find(params[:id])
    @owned_adventures = @user.adventures
    @attendances = @user.characters.flat_map do |character|
      character.attended_adventures.map { |adventure| [character, adventure] }
    end
    @characters = @user.characters.sorted_by_level
    @active_character = @user.active_character
  end

  def update
    @user = User.find(params[:id])
    if current_user && current_user.id == @user.id && @user.update(user_params)
      redirect_to @user, notice: "User bio updated successfully."
    else
      render :show
    end
  end

  private

  def user_params
    params.require(:user).permit(:bio, :timezone)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/show.html.erb
<% owner_mode = (current_user && @user.id == current_user.id) %>
<% past_adventures = [] %>
<% upcoming_adventures = [] %>
<% @attendances.each do |attendance|%>
  <% if attendance[1].date >= Date.today %>
    <% upcoming_adventures << attendance[1] %>
  <% else %>
    <% past_adventures << attendance[1] %>
  <% end %>
<% end %>

<div class="user user-show">
  <div class="main-title"><%= @user.username %></div>
  <div class="top-details">
    <% if owner_mode %>
      <%= button_to 'DELETE ACCOUNT', registration_path(current_user), method: :delete, data: { turbo_method: :delete, turbo_confirm: 'Are you sure you want to delete your account?' }, class: "btn delete-btn" %>
      <%= form_for @user, url: { action: "update" }, method: :patch do |f| %>
        <div class="main-details ridge-border">
          <div class="label">Bio</div>
          <div class="form-item">
            <%= f.text_area :bio, value: @user.bio, class: "form-control" %>
          </div>
          <div class="bottom">
            <div class="form-item">
              <div class="label">Timezone</div>
              <%= f.time_zone_select :timezone, nil, {}, class: "form-control" %>
            </div>
            <div class="actions">
              <%= f.submit "Update", class: "btn small-btn" %>
            </div>
          </div>
        </div>
      <% end %>
    <% else %>
      <div class="main-details ridge-border">
        <div class="bio"><%= @user.bio %></div>
        <div class="timezone"><span class="label">Timezone: </span> <%= @user.timezone %></div>
      </div>
    <% end %>
  </div>
  <div class="content">
    <div class="left-characters">
      <div class="title">Characters</div>
      <div class="character-list ridge-border">
        <% @characters.each do |character| %>
          <%= render 'shared/character_entry', character: character, is_active_char: (!@active_character.nil? && @active_character.id == character.id), creator_mode: false, img_size: "80x80" %>
        <% end %>
      </div>
        

      <!--
        <% @characters.each do |character|%>
          <li> <%= link_to character.name, character_path(character) %>: A level <%= character.level %> <%= character.gender %> <%= character.race %> <%= character.character_class %> (<%= character.ruleset %>)
          <% if character == @active_character %>
            <br>[active]
          <% else %>
            <br><%= link_to "[set active]", set_active_character_path(character), method: :patch, data: { turbo_method: :patch } %>
          <% end %> 
          <% if current_user && current_user.id == @user.id %>
            - <%= link_to "[edit]", edit_character_path(character) %>
          <% end %>
          </li>
        <% end %>
      </div>
      -->

      <% if current_user && current_user.id == @user.id %>
        <%= button_to "New Character", new_character_path, method: :get, class: "btn small-btn" %>
      <% end %>
    </div>
    <div class="right-adventures">
      <div class="title">Adventures</div>
      <div class="full-adventure-list">
        <% if @owned_adventures.count != 0 %>
        <div class="created-title adventures-title">Created</div>
        <div class="created-adventure-details adventures-details">
          <div class="adventure-list">
            <% @owned_adventures.order(date: :desc).each do |adventure| %>
              <%= render 'adventures/entry', adventure: adventure, attended_adventures: nil, mode: 'brief', rs_img: true %>
            <% end %>
          </div>
        </div>
        <% end %>

        <% if upcoming_adventures.count != 0 %>
        <div class="upcoming-title adventures-title">Upcoming</div>
        <div class="upcoming-adventure-details adventures-details">
          <div class="adventure-list">
            <% upcoming_adventures.sort_by { |adventure| adventure.date }.reverse.each do |adventure| %>
              <%= render 'adventures/entry', adventure: adventure, attended_adventures: nil, mode: 'brief', rs_img: true %>
            <% end %>
          </div>
        </div>
        <% end %>

        <% if past_adventures.count != 0 %>
        <div class="past-title adventures-title">Past</div>
        <div class="past-adventure-details adventures-details">
          <div class="adventure-list">
            <% past_adventures.sort_by { |adventure| adventure.date }.reverse.each do |adventure| %>
              <%= render 'adventures/entry', adventure: adventure, attended_adventures: nil, mode: 'brief', rs_img: true %>
            <% end %>
          </div>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</div>