config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  resources :adventures, only: [:index, :new, :create, :show, :edit, :update, :destroy ] do
    resources :messages, only: [:create]
    member do
      post 'attend'
    end
  end
  get 'adventures/intro', to: 'adventures#intro'
  
  resources :users, only: [:show, :update]

  resources :characters, only: [:show, :new, :create, :edit, :update, :destroy] do
    member do
      patch 'set_active'
    end
  end

  # Defines the root path route ("/")
  root "adventures#intro"
end

app/views/shared/_character_entry.html.erb
<% extra_class = is_active_char ? " active-char" : "" %>

<div class="character-entry">
  <div class="character-tooltip">
    <a href="<%= character_path(character) %>">
      <%= image_tag "portraits/#{character.portrait_path}", size: img_size, class: "character-img#{extra_class}" %>
    </a>
    <span class="character-tooltip-text">
      <b><%= character.name %></b><br>
      <%= character.character_class %> - Lv.<%= character.level %>
      <% if creator_mode %>
        (<%= character.user.email %>)
      <% end %>
    </span>
  </div>
</div>

app/views/shared/_ruleset_image.html.erb
  <% ruleset_num = 0 %>
  <% if defined?(character) %>
    <% ruleset_num = Character.rulesets[character.ruleset] %>
  <% elsif defined?(adventure) %>
   <% ruleset_num = Adventure.rulesets[adventure.ruleset] %>
  <% end %>
  <% ruleset_image = case ruleset_num
    when 0, 1
      "logos/dungeonsanddragons.png"
    when 2
      "logos/callofcthulhu.png"
    when 3
      "logos/Pathfinder1E.png"
    when 4
      "logos/Pathfinder2E.png"
    when 5
      "logos/warhammer.png"
    when 6
      "logos/Warhammer40k.png"
    when 7
      "logos/worldofdarkness.png"
    when 8
      "logos/apocalypseworld.png"
    when 9
      "logos/starwarsroleplaying.png"
    else
      "logos/starwarsroleplaying.png"
  end %>

  <%= image_tag ruleset_image, size: image_size, alt: "Ruleset Logo" %>

app/views/shared/_topbar.html.erb
<div class="top-bar">
  <a href="<%= root_path %>">
    <div class="top-logo">
      <%= image_tag "T3Logo.jpeg", size: "100x100"%>
      TableTop Tavern
    </div>
  </a>
  <div class="top-links">
    <%= button_to "ADVENTURES", adventures_path, method: :get, class: "btn" %>
    <% if user_signed_in? %>
      <%= button_to "PROFILE", user_path(current_user), method: :get, class: "btn" %>
      <%= button_to "SIGN OUT", destroy_user_session_path, class: "btn", method: :delete, data: { turbo_method: :delete, turbo_confirm: 'Are you sure you want to sign out?' } %>
    <% else %>
      <%= button_to "SIGN IN/SIGN UP", new_user_session_path, method: :get, class: "btn" %>
    <% end %>
  </div>
</div>