config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  resources :adventures, only: [:index, :new, :create, :show, :edit, :update, :destroy ] do
    resources :messages, only: [:create]
    member do
      post 'attend'
    end
  end
  get 'adventures/intro', to: 'adventures#intro'
  
  resources :users, only: [:show, :update]

  resources :characters, only: [:show, :new, :create, :edit, :update, :destroy] do
    member do
      patch 'set_active'
    end
  end

  # Defines the root path route ("/")
  root "adventures#intro"
end

app/models/adventure.rb
class Adventure < ApplicationRecord
  include Enums

  belongs_to :creator, class_name: "User"
  has_many :messages
  has_many :adventure_attendances, foreign_key: :attended_adventure_id, dependent: :destroy
  has_many :attendees, through: :adventure_attendances, source: :adventure_attendee

  scope :past, -> { where('date < ?', DateTime.now) }
  scope :upcoming, -> { where('date >= ?', DateTime.now) }
  scope :by_ruleset, -> (ruleset) { where('ruleset = ?', ruleset) }
  scope :by_level_range, ->(min_lvl, max_lvl) { where('min_level >= ? AND max_level <= ?', min_lvl, max_lvl) }
  scope :compatible_with_active_character, lambda  { |user|
    if user.active_character.present?
      where('adventures.ruleset = ? AND min_level <= ? AND max_level >= ?', 
      Character.rulesets[user.active_character.ruleset], 
      user.active_character.level, 
      user.active_character.level) 
    end
  }
  scope :open, lambda {
    left_joins(:adventure_attendances)
      .group(:id)
      .having('COUNT(adventure_attendances.id) < adventures.max_seats')
  }
  scope :virtual, -> { where('platform > ?', 2) }
  scope :in_person, -> { where('platform <= ?', 2) }
  scope :is_public, -> { where('is_private = ?', false) }
  scope :is_private, -> { where('is_private = ?', true) }
  scope :attending, ->(user) { joins(attendees: :user).where('characters.user_id = ?', user.id) }

  validates :name, presence: true, length: { maximum: 40 }
  validates :module, length: { maximum: 40 }
  validates :description, presence: true, length: { maximum: 500}
  validates :max_seats, numericality: { only_integer: true, greater_than: 0, less_than_or_equal_to: 10 }
  validates :min_age, numericality: { only_integer: true, greater_than: 0, less_than_or_equal_to: 99 }
  validates :min_level, numericality: { only_integer: true, greater_than_or_equal_to: 0, less_than: 99 }
  validates :max_level, numericality: { only_integer: true, greater_than: 0, less_than_or_equal_to: 99 }

end

app/controllers/adventures_controller.rb
class AdventuresController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy, :attend]

  def intro
    @adventures = Adventure.upcoming.is_public.order(date: :asc).limit(5)

    return unless current_user

    @attending_adventures = @adventures.attending(current_user)
  end

  def index
    @adventures = Adventure.all

    #Filter by public only
    @adventures = @adventures.is_public

    if params[:filter].present? && params[:filter] == 'match' && current_user
      @adventures = @adventures.compatible_with_active_character(current_user)
      @attended_adventures = @adventures.attending(current_user)
      render :index
      return
    end
    
    # Filter: Past vs upcoming
    if params[:time].present?
      @adventures = params[:time] == 'upcoming' ? @adventures.upcoming : @adventures.past
    end
    
    # Filter: Ruleset
    if params[:ruleset].present?
      if params[:ruleset] == 'active_character' && current_user && current_user.active_character
        @adventures = @adventures.by_ruleset(active_character.ruleset)
      elsif params[:ruleset] != 'all' && params[:ruleset] != 'active_character'
        @adventures = @adventures.by_ruleset(params[:ruleset])
      end
    end
 
    # Filter: open
    @adventures = @adventures.open if params[:vacancy].present?

    # Filter: by level
    min_level = params[:min_level].present? ? params[:min_level] : 0
    max_level = params[:max_level].present? ? params[:max_level] : 99
    @adventures = @adventures.by_level_range(min_level, max_level)

    # Filter: by platform (in person vs VTT)
    if params[:platform].present?
      @adventures = params[:platform] == 'virtual' ? @adventures.virtual : @adventures.in_person
    end

    #Put in date order
    @adventures = @adventures.order(date: :asc).includes(:creator)

    # Make a single database call for counts, for optimization purposes
    @attendee_counts = AdventureAttendance.group(:attended_adventure_id).count

    return unless current_user

    @attended_adventures = @adventures.attending(current_user)
  end

  def show
    @adventure = Adventure.find(params[:id])
    
    return unless current_user

    @attended_adventures = Adventure.attending(current_user)

    # Only adventure creator and attending users can actually see or post messages in chat
    return unless @adventure.creator_id == current_user.id || @attended_adventures.exists?(@adventure.id)

    @message = Message.new
    @messages = @adventure.messages
  end

  def edit
    @adventure = Adventure.find(params[:id])
  end

  def update
    @adventure = Adventure.find(params[:id])

    # Only allow creators to edit the adventure
    if current_user && @adventure.creator_id == current_user.id
      if @adventure.update(adventure_params)
        flash[:notice] = "Adventure successfully edited."
        redirect_to adventure_path(@adventure)
      else
        render :edit, status: :unprocessable_entity
      end
    else
      flash[:alert] = "You are not this adventure's creator."
      render :edit, status: :unprocessable_entity
    end
  end

  def new
    @adventure = current_user.adventures.build() if current_user
  end

  def create
    @adventure = current_user.adventures.build(adventure_params) if current_user
    
    if @adventure.save
      redirect_to current_user
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @adventure = Adventure.find(params[:id])
    if current_user && current_user.id == @adventure.creator_id 
      if @adventure.destroy
        flash[:notice] = 'Adventure was successfully deleted.'
      else
        flash[:alert] = 'Failed to delete the adventure.'
      end
    else
      flash[:alert] = 'Only adventure creator can destroy it.'
    end
    redirect_to adventures_path
  end

  def attend
    @adventure = Adventure.find(params[:id])

    if !current_user
      flash[:alert] = "Error: Must be logged in."
      render :show, status: :unprocessable_entity
      return
    end

    character_to_remove = current_user.characters.find do |character|
      @adventure.attendees.include?(character)
    end

    # Remove attendance if already attending
    unless character_to_remove.nil?
      character_to_remove.attended_adventures.delete(@adventure)
      redirect_to @adventure, notice: "#{character_to_remove.name} is no longer attending this adventure."
      return
    end

    if current_user.active_character.nil?
      flash[:alert] = "Error: No active character"
      render :show, status: :unprocessable_entity
      return
    end

    # Otherwise attempt to attend
    if current_user.active_character.level >= @adventure.min_level && current_user.active_character.level <= @adventure.max_level
      if current_user.birthdate + @adventure.min_age.years < Time.now
        if @adventure.attendees.count < @adventure.max_seats
          current_user.active_character.attended_adventures << @adventure
          redirect_to @adventure, notice: "#{current_user.active_character.name} is now attending this adventure."
        else
          flash[:alert] = "Adventure is full."
          render :show, status: :unprocessable_entity
        end
      else
        flash[:alert] = "You do not meet minimum age requirements."
        render :show, status: :unprocessable_entity
      end
    else
      flash[:alert] = "Character level is not within min/max of adventure."
      render :show, status: :unprocessable_entity
    end
  end

  private

  def adventure_params
    params.require(:adventure).permit(:name, :date, :ruleset, :module, :description, :platform, 
                                      :max_seats, :min_age, :min_level, :max_level, :address, :is_private)
  end

end

app/helpers/adventures_helper.rb
module AdventuresHelper
  def formatted_date(date)
    if user_signed_in?
      date = date.in_time_zone(current_user.timezone)
    else
      date = date.in_time_zone("Eastern Time (US & Canada)")
    end
    # Format the date, e.g.: Nov 21, 2023 - 4:25 pm
    if user_signed_in?
      date.strftime('%b %-d, %Y - %l:%M %P')
    else
      date.strftime('%b %-d, %Y - %l:%M %P') + ' EST'
    end
  end
end

app/views/adventures/_entry.html.erb
<a href="<%= adventure_path(adventure) %>">

<% entry_class = "" %>
<% if current_user %>
  <% entry_class = "creator-entry" if current_user.id == adventure.creator_id %>
  <% entry_class = "attendee-entry" if !attended_adventures.nil? && attended_adventures.pluck(:id).include?(adventure.id) %>
<% end %>

<div class="adventure-entry <%= entry_class %>">
  <% if rs_img %>
    <%= render 'shared/ruleset_image', image_size: "100x50", adventure: adventure %>
  <% end %>
  <div class="title"><%= adventure.name %></div>
  <div class="details">
    <div class="detail"><b>Date:</b> <%= formatted_date(adventure.date) %></div> 
    <div class="detail"><b>Levels:</b> <%= adventure.min_level %> to <%= adventure.max_level %></div>  
    <div class="detail"><b>Hosted by:</b> <%= adventure.creator.username %> <i><% if Adventure.platforms[adventure.platform] > 2 %>virtually<% else %>in-person<% end %></i></div>             
  </div>
  <% if mode == 'full'%>
    <div class="seats">
      <%= (attendee_counts[adventure.id] || 0) %> / <%= adventure.max_seats %> 
    </div>
  <% end %>
</div>
</a>

app/views/adventures/_form.html.erb
<%= form_for @adventure, html: {'data-controller' => 'adventure-form'} do |f| %>
  <div class="form-controls ridge-border colored">
    <div class="form-item">
      <%= f.label :date %>
      <%= f.datetime_local_field :date, :data => { :adventure_form_target => "date" }, class: 'form-control long', required: true %>
    </div>

    <div class="form-item">
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control long', maxlength: 40, required: true %>
    </div>

    <div class="form-item">
      <%= f.label :ruleset %>
      <%= f.select :ruleset, Adventure.rulesets.keys, {}, class: 'form-control' %>
    </div>

    <div class="form-item">
      <%= f.label :module %>
      <%= f.text_field :module, class: 'form-control long', maxlength: 40 %>
    </div>

    <div class="form-item">
      <%= f.label :description %>
      <%= f.text_area :description, class: 'form-control description long', maxlength: 500, required: true %>
    </div>

    <div class="form-item">
      <%= f.label :platform %>
      <%= f.select :platform, Adventure.platforms.keys, {}, class: 'form-control' %>
    </div>

    <div class="form-item">
      <%= f.label :max_seats %>
      <%= f.number_field :max_seats, in: 1..10, class: 'form-control', required: true %>
    </div>

    <div class="form-item">
      <%= f.label :min_age %>
      <%= f.number_field :min_age, in: 0..99, class: 'form-control', required: true %>
    </div>

    <div class="form-item">
      <%= f.label "Level: " %>
      <%= f.number_field :min_level, in: 1..99, :data => { :adventure_form_target => "min" }, class: 'form-control', required: true %>
      to
      <%= f.number_field :max_level, in: 1..99, :data => { :adventure_form_target => "max" }, class: 'form-control', required: true %>
    </div>

    <div class="form-item">
      <%= f.label :address %>
      <%= f.text_field :address, class: 'form-control' %>
    </div>

    <div class="form-item">
      <%= f.label :is_private %>
      <%= f.check_box :is_private, class: 'form-check-input' %>
    </div>
  </div>

  <div class="form-item">
    <% button_text = mode == 'new' ? 'Create Adventure' : 'Update Adventure' %>
    <%= f.submit button_text, :data => { :action => "click->adventure-form#validate" }, class: 'btn small-btn' %>
  </div>
<% end %>

<% if @adventure.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@adventure.errors.count, "error") %> prohibited this adventure from being saved:</h2>
    <ul>
      <% @adventure.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/adventures/edit.html.erb
<div class="adventure adventure-edit">
  <div class="title">Edit Adventure</div>

  <% if current_user && @adventure.creator_id == current_user.id %>
    <%= render 'form' , mode: 'edit' %>
  <% else %>
    <h3>ERROR: You did not create this adventure and therefore cannot edit it.</h3>
  <% end %>

</div>

app/views/adventures/index.html.erb
<div class="adventure adventure-index">
  <%= form_tag(adventures_path, method: 'get', class: 'filter-form') do %>
    <div class="filters">
      <div class="form-item">
        <%= label_tag :time, "Time:" %>
        <%= select_tag 'time', options_for_select([['All', nil], ['Upcoming', 'upcoming'], ['Past', 'past']], params[:time]), class: 'form-control' %>
      </div>

      <div class="form-item">
        <%= label_tag :vacancy, "Vacancy:" %>
        <%= select_tag 'vacancy', options_for_select([['All', nil], ['Open', 'open']], params[:vacancy]), class: 'form-control' %>
      </div>

      <div class="form-item">
        <%= label_tag :ruleset, "Ruleset:" %>
        <%= select_tag 'ruleset', options_for_select([['All', 'all'], ['Active-char', 'active_character']] + Adventure.rulesets.map { |k, v| [k.humanize, v] }, params[:ruleset]), class: 'form-control' %>
      </div>

      <div class="form-item">
        <%= label_tag :platform, "Platform:" %>
        <%= select_tag 'platform', options_for_select([['All', nil], ['In-Person', 'in_person'], ['Virtual', 'virtual']], params[:platform]), class: 'form-control' %>
      </div>

      <div class="form-item">
        <%= label_tag :min_level, "Min Level:" %>
        <%= number_field_tag 'min_level', params[:min_level], class: 'form-control form-lvl', placeholder: '0', min: 0, max: 99 %>
      </div>
      <div class="form-item">  
        <%= label_tag :max_level, "Max Level:" %>
        <%= number_field_tag 'max_level', params[:max_level], class: 'form-control form-lvl', placeholder: '99', min: 0, max: 99 %>
      </div>
    </div>

    <div class="side-buttons">
      <div class="form-buttons">
        <%= button_tag 'Apply Filters', type: :submit, value: 'default', class: 'btn small-btn', name: 'filter' %>
        <% if current_user && current_user.active_character.present? %>
          <%= button_tag 'Match Active', type: :submit, value: 'match', class: 'btn small-btn', name: 'filter' %>
        <% end %>
      </div>

      <% if current_user && current_user.active_character.present? %>
      <div class="activechar">
        <div class="activechar-tooltip">
          <a href="<%= character_path(current_user.active_character)%>">
            <%= image_tag "portraits/#{current_user.active_character.portrait_path}", size: "80x80" %>
          </a>
          <span class="activechar-tooltip-text">
            <b><%= current_user.active_character.name %></b>
            <br>
            <%= current_user.active_character.character_class %> - Lv.<%= current_user.active_character.level %>
            <br>
            Ruleset: <%= current_user.active_character.ruleset %>
          </span>
        </div>
      </div>
      <% end %>

    </div>
  <% end %>
  <div class="content">
    <div class="button-container">
      <% if current_user %>
        <%= button_to "NEW ADVENTURE", new_adventure_path, method: :get, class: 'btn' %>
      <% end %>
    </div>
    <div class="adventure-content">
      <div class="adventure-list-title">Adventure List</div>
      <div class="adventure-list">
        <% @adventures.each do |adventure|%>
          <%= render 'entry', adventure: adventure, attended_adventures: @attended_adventures, attendee_counts: @attendee_counts, mode: 'full', rs_img: true %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/adventures/intro.html.erb
<div class="adventure adventure-intro">
  <div class="text-intro">
    <h1>"Welcome to TableTop Tavern!"</h1>
    <p>"Kick up yer boots, traveler, and grab an ale. Take a look at our Adventure Board, a listing of adventures from all 'cross the multiverse."</p>
  </div>

  <div class="middle-content">
    <div class="left">
      <%= image_tag "tavernkeeper.jpeg", size: "450x450", alt: "Tavernkeeper Image", class: "innkeeper" %>
    </div>

    <div class="right">
      <h2>Upcoming Adventures</h2>
      <div class="adventure-list">
      <% @adventures.each do |adventure| %>
        <%= render 'entry', adventure: adventure, attended_adventures: @attended_adventures, mode: 'brief', rs_img: true %>
      <% end %>
        <a href="<%= adventures_path %>">
          <div class="adventure-entry find-more">
            <div>FIND MORE</div>
          </div>
        </a>
      </div>
    </div>
  </div>
</div>

app/views/adventures/new.html.erb
<div class="adventure adventure-new">
  <div class="title">Create a New Adventure</div>

  <%= render 'form' , mode: 'new' %>

</div>

app/views/adventures/show.html.erb
<% creator_mode = false %>
<% if (current_user && @adventure.creator.id == current_user.id) %>
  <% creator_mode = true %>
<% end %>

<div class="adventure adventure-show">
  <div class="main-title"><%= @adventure.name %></div>
  <div class="content">
    <div class="main-details ridge-border colored">
      <%= render 'shared/ruleset_image', image_size: "200x100", adventure: @adventure %>
      <div class="main-hosted">Hosted by: <%= link_to @adventure.creator.username, user_path(@adventure.creator) %> </div>
    </div>
    <div class="secondary-details">
      <% if !@adventure.is_private || creator_mode %>
        <div class="details ridge-border colored">
          <div class="time">Occurring on <%= formatted_date(@adventure.date) %></div>
          <br>
          <% if !@adventure.module.nil? && @adventure.module != "" %>
            <div class="detail"><span class="label"><b>Module:</b></span> <%= @adventure.module %> </div>
          <% end %>
          <div class="detail"><span class="label"><b>Platform:</b></span> <%= @adventure.platform %> </div>
          <% if @adventure.platform == "InPersonPublic" || creator_mode %>
            <div class="detail"><span class="label"><b>Address:</b></span> <%= @adventure.address %> <% if creator_mode && @adventure.platform == "InPersonHome" %>(Not public)<% end %></div>
          <% end %>
          <div class="detail"><span class="label"><b>Level:</b></span> <%= @adventure.min_level%> to <%= @adventure.max_level %></div>
          <div class="detail"><span class="label"><b>Minimum Age:</b></span> <%= @adventure.min_age %></div>
          <br>
          <div class="description"><%= @adventure.description %></div>
        </div>
        
        <div class="attendees-details ridge-border colored">
          <div class="attendees-title">Attendees (<%= @adventure.attendees.count %> / <%= @adventure.max_seats %>)</div>
          <div class="attendees">
            <% @adventure.attendees.each do |attendee| %>
              <%= render 'shared/character_entry', character: attendee, is_active_char: false, creator_mode: creator_mode, img_size: "80x80" %>
            <% end %>
          </div>
        </div>

        <div class="actions">
          <% attending = !@attended_adventures.nil? && @attended_adventures.exists?(@adventure.id) %>
          <% if current_user && !creator_mode && (attending || (!current_user.active_character.nil? && 
                current_user.active_character.level >= @adventure.min_level && 
                current_user.active_character.level <= @adventure.max_level && 
                current_user.birthdate + @adventure.min_age.years < Time.now && 
                @adventure.attendees.count < @adventure.max_seats)) %>
            <%= form_for @adventure, url: attend_adventure_path(@adventure), method: :post, remote: true do |f| %>
              <% attend_text = attending ? 'Unattend Adventure' : 'Attend Adventure' %>
              <%= f.submit attend_text, class: 'btn small-btn' %>
            <% end %>
            <% if flash[:alert] %><div class="flash alert"><%= flash[:alert] %></div><% end %>
          <% elsif creator_mode %>
            <%= form_for @adventure, url: adventure_path(@adventure), method: :patch do |f| %>
              <% if @adventure.is_private %>
                <%= f.hidden_field :is_private, value: false %>
                <%= f.submit 'Make Public', class: 'btn small-btn' %>
              <% else %>
                <%= f.hidden_field :is_private, value: true %>
                <%= f.submit 'Make Private', class: 'btn small-btn' %>
              <% end %>
            <% end %>
            <%= button_to "Edit", edit_adventure_path(@adventure), class: 'btn small-btn', method: :get %>
            <%= button_to "Delete", adventure_path(@adventure), class: 'btn small-btn', method: :delete, data: { turbo_method: :delete, turbo_confirm: 'Are you sure you want to delete this adventure?' } %>
          <% end %>
        </div>

      <% else %>
        <div class="details">Adventure is currently marked private</div>
      <% end %>
    </div>
    <% if current_user && (creator_mode || attending) %>
    <div class="chat ridge-border colored" data-controller="chat">
      <div id="message-display" data-chat-target="chatbox">
        <% @messages.each do |message| %>
          <div class="message">
              <strong><%= message.username %>:</strong> <%= message.body %>
          </div>
        <% end %>
      </div>
      <div id="message-form">
        <%= form_with model: [@adventure, @message], :data => { :chat_target => "form" } do |f| %>
          <div class="chat-entry">
            <hr>
            <div class="form-item">
              <%= f.text_field :body, id: 'message-input', :data => { :chat_target => "textbox" }, class: 'form-control' %>
            </div>
            <div class="form-item">
              <%= f.hidden_field :adventure_id, id: 'adventure-id', value: @adventure.id %>
              <%= f.submit 'Send Message', class: 'btn small-btn', :data => { :action => "click->chat#submit" } %>
            </div>
          </div>
        <% end %>
      </div>
      <% if @message.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@message.errors.count, "error") %> prohibited this message from being saved:</h2>
          <ul>
            <% @message.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
    </div>
    <% end %>
  </div>
</div>